spring.application.name=portfolio-api
server.port=${SERVER_PORT}
server.ssl.enabled=false
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
