spring.application.name=portfolio-api
server.port=${SERVER_PORT}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
server.ssl.enabled=false
server.forward-headers-strategy=framework
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false